### ISSUE TITLE
How to kick off to work? No results.

### ISSUE THREAD

**Issue by drupality** [elvetemedve/behat-screenshot#22]
My config:
```
default:
  extensions:
    Bex\Behat\ScreenshotExtension:
      image_drivers:
        local:
          screenshot_directory: '/var/www/project/tests/failures'
```
Test ouput: 

```
alExtension\Context\MinkContext::assertTextVisible()
    And I should see the text "The requested product Test Product is currently not available for this country" # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()
      The text "The requested product Test Product is currently not available for this country" was not found anywhere in the text of the current page. (Behat\Mink\Exception\ResponseTextException)

--- Failed scenarios:

    features/product.feature:12

1 scenario (1 failed)
7 steps (6 passed, 1 failed)
```

No message, no screenshot.

What am I doing wrong? behat version 3.0.15
