### ISSUE TITLE
No image or 0b image generated

### ISSUE THREAD

**Issue by golddragon007** [elvetemedve/behat-screenshot#38]
I have this settings:

behat.yml:
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      javascript_session: selenium2
      base_url: http://somesite.dd:8083
      #goutte: ~
      selenium2:
        browser: firefox
        wd_host: http://localhost:4444/wd/hub
    Drupal\DrupalExtension:
      blackbox: ~
    Bex\Behat\ScreenshotExtension:
      image_drivers:
        local:
          screenshot_directory: screenshots
          clear_screenshot_directory: true  # Enable removing all images before each test run. It is false by default.
```

composer.json:
```
{
    "name": "drupal-composer/drupal-project",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "GPL-2.0+",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        "leaflet": {
            "type": "package",
            "package": {
                "name": "leaflet/leaflet",
                "version": "v0.7.7",
                "type": "drupal-library",
                "dist": {
                    "url": "https://github.com/Leaflet/Leaflet/archive/v0.7.7.zip",
                    "type": "zip"
                }
            }
        }
    },
    "require": {
        "composer/installers": "^1.2",
        "drupal-composer/drupal-scaffold": "^2.2",
        "cweagans/composer-patches": "~1.0",
        "drupal/core": "~8.0",
        "drush/drush": "~8.0",
        "drupal/console": "~1.0",
        "drupal/paragraphs": "^1.0",
        "drupal/admin_toolbar": "^1.18",
        "drupal/addtoany": "^1.7",
        "drupal/pathauto": "^1.0@beta",
        "drupal/imagemagick": "^1.0@alpha",
        "drupal/tvi": "^1.0@beta",
        "drupal/google_analytics": "^2.1",
        "drupal/webform": "5.0-beta7",
        "drupal/parade": "2.x-dev",
        "drupal/drupal-extension": "^3.3"
    },
    "require-dev": {
        "behat/mink": "~1.7",
        "behat/mink-goutte-driver": "~1.2",
        "jcalderonzumba/gastonjs": "~1.0.2",
        "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
        "mikey179/vfsStream": "~1.2",
        "phpunit/phpunit": "~4.8",
        "symfony/css-selector": "~2.8",
        "drupal/devel": "1.x-dev",
        "bex/behat-screenshot": "^1.2",
        "behat/mink-selenium2-driver": "^1.3",
        "phpspec/phpspec": "^3.4",
        "bex/behat-test-runner": "^1.2",
        "jakoch/phantomjs-installer": "^2.1"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ]
    },
    "scripts": {
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        }
    }
}
```

And my problem is, when I add 'goutte: ~' on selenium2 level, my test works well, but it doesn't generate any image. If I remove that line, I get a 0b image, but all my tests fails (those too, which needs to be passed and passed with 'goutte: ~'). How do I need to use this?

**Comment by elvetemedve** [comment]
Hi @golddragon007,
Goutte mink extension is an adapter for the [Goutte Web Sraper](https://github.com/FriendsOfPHP/Goutte), which does not render the HTML pages, therefore not capable of taking screenshots. It only cares about talking the HTTP protocol. That's why it's very fast compared to the Selenium driver which actually controls a real browser. 

So if you want screenshots, you need to use the Mink driver which is capable of taking screenshots. I suggest Selenium, because it's widely used.

If you want **screenshots for all scenarios**, you can setup Selenium as default like:
```
# ...
extensions:
    Behat\MinkExtension:
      default_session: selenium2
      base_url: http://somesite.dd:8083
      selenium2:
        browser: firefox
        wd_host: http://localhost:4444/wd/hub
# ...
```
If you want to use the fast **Goutte driver by default**, but want to run some of your scenarios by Selenium, you can set up Behat like:
```
# ...
extensions:
    Behat\MinkExtension:
      default_session: goutte
      javascript_session: selenium2
      base_url: http://somesite.dd:8083
      goutte: ~
      selenium2:
        browser: firefox
        wd_host: http://localhost:4444/wd/hub
# ...
```
Now you need to mark your desired scenarios with the `@javascript` [tag](http://behat.org/en/latest/user_guide/organizing.html) in order to select Selenium for them.

I hope that helps.

**Comment by golddragon007** [comment]
Hi @elvetemedve 

```
extensions:
    Behat\MinkExtension:
      default_session: selenium2
      base_url: http://somesite.dd:8083
      selenium2:
        browser: firefox
        wd_host: http://localhost:4444/wd/hub
```

It's still don't want to work, same issue as before. Do I need to run something, or I just need to run behat test with these settings...?
