### ISSUE TITLE
Requirements clarification

### ISSUE THREAD

**Issue by leymannx** [elvetemedve/behat-screenshot#44]
Trying to find my path to screenshots in Behat tests one thing is still unclear to me:

To make use of this pretty nice tool (❤️) we need a JavaScript session with for example Selenium or PhantomJS, yes?

As we need a browser in the first place, is this right?

For example I have the following `behat.yml` were screenshots are only taken for `@javascript` tagged scenarios. And I guess that's how it's supposed to work, yes?

```yaml
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      base_url: http://foobar.localhost
      goutte: ~
      selenium2: ~
    Drupal\DrupalExtension:
      blackbox: ~
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: all_scenarios
      image_drivers:
        local:
          screenshot_directory: /tmp/screenshots
```

**Comment by leymannx** [comment]
Uh, suddenly it started to work also for non-`@javascript` tagged scenarios after I added `wd_host` and `browser_name` to make use of Selenium's WebDrivers.

```yaml
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Behat\MinkExtension:
      base_url: http://foobar.localhost
      goutte: ~
      selenium2:
        wd_host: "http:/foobar.localhost:4444/wd/hub"
      browser_name: chrome
    Drupal\DrupalExtension:
      blackbox: ~
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: all_scenarios
      image_drivers:
        local:
          screenshot_directory: /tmp/screenshots
```
