### ISSUE TITLE
Screenshot only works on javascript scenarios?

### ISSUE THREAD

**Issue by golddragon007** [elvetemedve/behat-screenshot#47]
I have this settings:
```
  extensions:
    Behat\MinkExtension:
      browser_name: 'chrome'
      goutte: ~
      selenium2:
        wd_host: 'http://localhost:4444/wd/hub'
        browser: 'chrome'
        capabilities:
          browser: 'chrome'
          chrome:
            switches:
            - "--headless"
            - "--disable-gpu"
      javascript_session: 'selenium2'
      base-url: 'http://localhost:8080/my-site'
      files_path: '/home/user/environment/my-site'
    Drupal\DrupalExtension:
      api_driver: 'drupal'
      blackbox: ~
      drupal:
        drupal_root: '/home/user/environment/my-site'
      selectors:
        message_selector: '.messages'
        error_message_selector: '.messages.error'
        success_message_selector: '.messages.status'
      subcontexts:
        paths:
        - '/home/user/environment/my-site/sites/default'
      drush:
        alias: 'default'
        binary: '/home/user/environment/my-site/vendor/package/toolkit/bin/drush'
      region_map:
        header: "#layout-header"
        featured: ".region-featured-wrapper"
        content_top: ".content-top"
        content: "#content-wrapper"
        left sidebar: "#sidebar-left"
        right sidebar: "#sidebar-right"
        footer: "#layout-footer"
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_scenarios
      image_drivers:
        local:
          screenshot_directory: '/home/user/environment/my-site/tests/screenshots'
          clear_screenshot_directory: true
  formatters:
    pretty: ~
```

And I noticed it only creates screenshots from the failed scenarios if the scenario is annotated as a javascript scenario. It's not possible to create screenshot if it's not annotated like that? And some why on the screenshot I can see only the text without css... But form the browser it works...
